#!/bin/sh
# Copyright 2018 ANSSI
# Distributed under the terms of the GNU General Public License v2
#
# Reassign ownership of the console to root, this should disallow
# assignment of console output to any random users's xterm

USER="${1}"

chmod 622 /dev/console
chown root /dev/console
/usr/local/bin/sessreg -d -w "/var/log/wtmp" -u "/var/run/utmp" \
	-l $DISPLAY -h "" $USER

if [[ -x /usr/local/bin/netchoose ]]; then
	. /etc/init.d/network-common
	netlist_update
fi
